version: '2'
services:
  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    ports:
      - "8500:8500"
  microapi:
    image: microhq/micro
    command: api --address=0.0.0.0:8080
    ports:
      - "80:8080"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_API_NAMESPACE=go.micro.api
      - MICRO_API_HANDLER=rpc
    links:
      - consul
      - service.greeter
  service.greeter:
      build:
        dockerfile: ./dockerfile
        context: ./
      image: greeter
      environment:
        - MICRO_REGISTRY=consul
        - MICRO_REGISTRY_ADDRESS=consul
      links:
        - consul
      